
$(eval $(call addlib,apphelloocaml))

LIBS := $(UK_LIBS)/musl:$(UK_LIBS)/ocaml

APPHELLOOCAML_OBJS-y += $(APPHELLOOCAML_BASE)/_build/default/src/program.exe.o

.PHONY: 
$(APPHELLOOCAML_BASE)/_build/default/src/program.exe.o: $(APPHELLOOCAML_BASE)/src/dune $(APPHELLOOCAML_BASE)/src/program.ml $(APPHELLOOCAML_BASE)/src/stubs.c
	cd $(APPHELLOOCAML_BASE) && \
		CFLAGS="$(CFLAGS) $(CFLAGS-y) $(CINCLUDES) $(CINCLUDES-y)" \
		dune build src/

